---
- name: install HDP sandbox
  hosts: hdps
  become: yes
  tasks:
    - name: create dir for scripts
      file:
        path: /opt/hdp
        state: directory
    - name: install unzip
      apt:
        name: unzip
        state: present
    - name: Download and unarchive install script
      unarchive:
        src: https://archive.cloudera.com/hwx-sandbox/hdp/hdp-2.6.5/HDP_2.6.5_deploy-scripts_180624d542a25.zip
        dest: /opt/hdp
        remote_src: yes
    - name: modify /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ansible_host}} sandbox-hdp.hortonworks.com sandbox-hdf.hortonworks.com"
    - name: start HDP
      shell: cd /opt/hdp && /bin/bash docker-deploy-hdp265.sh
